### ISSUE TITLE
Unhandled promise rejection when turning on polling while Hyperdeck is disconnected

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-hyperdeck#19]
1. Create a Hyperdeck module
2. Make sure your Hyperdeck is disconnected
3. In the config settings, click the "Enable Timecode Polling?" check box
4. Click apply

In the build version, it will continually throw this error at the polling interval:
<img width="425" alt="74576815-2aab3f80-4f52-11ea-8276-e8700622cd33" src="https://user-images.githubusercontent.com/50299051/75776680-0bfec400-5d1a-11ea-8277-88033a669930.png">

In dev mode, it's indicating there's an unhandled promise rejection:

<img width="570" alt="Screen Shot 2020-03-03 at 6 38 36 AM" src="https://user-images.githubusercontent.com/50299051/75776634-f5586d00-5d19-11ea-98af-e92465c4d354.png">

**Comment by krocheck** [comment]
@bryce-seifert the stacktrace listed indicates the Mikrotik module is throwing the error.  Can you disable it, try again, and provide any update error captures.

**Comment by bryce-seifert** [comment]
I don’t have that module installed.

**Comment by krocheck** [comment]
Which build are you running?

**Comment by bryce-seifert** [comment]
2140, but it's been present since at least 2050.

**Comment by bryce-seifert** [comment]
@krocheck After some testing, I think I caught this error here:
https://github.com/bitfocus/companion-module-hyperdeck/pull/16/commits/5df14dbfab848adc3b6b97cae596d3bb96660bbd

**Comment by krocheck** [comment]
Ok, that's fine, but can someone please explain how this is causing the mikrotik module to throw an error.

**Comment by baltedewit** [comment]
> but can someone please explain how this is causing the mikrotik module to throw an error.

Because the microtik library uses a global catch for unhandled promises, assuming that all promises are originating from it's own library and thus will have a `.cmd` property: https://github.com/Trakkasure/mikronode/blob/1575680c6d0068f5182511ec70725683cbe3ef3c/src/Util.js#L138

It's never a bad thing to handle a promise rejection, so I feel good about that commit but this _really_ should be changed in the mikrotik library as it will create errors (property cmd not found) from warnings (promise rejection)

**Comment by krocheck** [comment]
@baltedewit well that's a fun one!

I suppose I'm unclear how that library would even be listening since mikrotik wasn't even instantiated.  Can we address this in our mikrotik module or does this really need to be addressed upstream?

Damn I really need to read up on this promise thing now ... new concept compared to the languages I'm used to.

**Comment by baltedewit** [comment]
> I suppose I'm unclear how that library would even be listening since mikrotik wasn't even instantiated. Can we address this in our mikrotik module or does this really need to be addressed upstream?

As soon as the module is in a `require` that code will execute. So the `require` could be moved within our module but really a library shouldn't handle any errors or events coming from outside of the library itself so I'd say that it needs to be fixed in the microtik library anyway.

**Comment by JeffreyDavidsz** [comment]
@baltedewit thanks for this! The require of mikrotik is in the module mikrotik and in the hyperdeck issue it wasn't loaded. So we need to check how this could happen. I can look if I can catch an error in the mikrotik module and log it. For now the hyperdeck will catch the error by itself, looking at the latest pull request

**Comment by willosof** [comment]
I suggest removing the mikrotik module until this is fixed.

**Comment by JeffreyDavidsz** [comment]
Not needed, let's look at Julian's put request first

**Comment by bryce-seifert** [comment]
Resolved for Hyperdeck with https://github.com/bitfocus/companion-module-hyperdeck/pull/16
