### ISSUE TITLE
Feedback for Blackmagic HyperDeck

### ISSUE THREAD

**Issue by Fader-Monkey** [bitfocus/companion-module-hyperdeck#3]
Feedback module for Blackmagic Hyperdeck 
Requested modules 
1. Recording state 
2. Disk status (Disk/NoDisk) 

Not platform dependent 

usecases
Recording state: easy visual feedback to see if recordings are running
Disk status: able to see if the disks are loaded when away from the gear

**Comment by gabrielve1** [comment]
Hello there? Any news on the horizon maybe ? :) That feedback function for Hyperdeck module would be very useful.

**Comment by krocheck** [comment]
It's on my list.  Getting a few other things off my plate (and my hyperdecks over to the office from the warehouse).

**Comment by krocheck** [comment]
@sphlabs did you get anywhere with this? (see my above comment)

**Comment by mhohman** [comment]
Feedback would be killer for us! We have a streamdeck remotely mounted at FOH and the ability for them to verify that the decks are rolling as a backup would be amazing.

**Comment by JeffreyDavidsz** [comment]
If someone has the response of the machine, I could start with it

**Comment by thingyt** [comment]
Relevant info starts on Page 62 (commands and options) and the specific return info for the transport command is on page 68. 
I deleted the rest of the languages from the PDF manual before uploading to save on space as it was over 30MB and 600 pages.
[HyperDeckManual English Only.pdf](https://github.com/bitfocus/companion-module-hyperdeck/files/3428771/HyperDeckManual.English.Only.pdf)

**Comment by bryce-seifert** [comment]
Chiming in since this seems related to [my feature request](https://github.com/bitfocus/companion-module-hyperdeck/issues/13). Although a little different since that is for $() button variables and this is for feedback. 

But I clipped some of the relevant portions from the manual that would help implement this:

> Recording state
transport info ↵
208 transport info:↵
status: {“preview”, “stopped”, “play”, “forward”, “rewind”,
“jog”, “shuttle”,”record”}↵

> Disk status (Disk/NoDisk)
slot info↵
202 slot info:↵
status: {"empty", "mounting", "error", "mounted"}↵

> I really would like to have the timecode running in a button 
transport info ↵
timecode: {timecode}↵

> Is there any way to see how many seconds remaining on a clip, and show that on a button?
It seems there may not be a way to do this directly. But, I wonder if this could grab the duration:
transport info ↵
208 transport info:↵
clip id: {Clip ID or “none”}↵

And then once you have the ID of the clip playing, get the total timecode:
clips get↵
205 clips info:↵
{Clip ID}: {Name} {Start timecode} {Duration timecode}↵

And then subtract that from
transport info ↵
timecode: {timecode}↵

**Comment by baltedewit** [comment]
Feedback for transport status and slot status was added in #10 

I haven't looked into clip ID's or timecode.

**Comment by bryce-seifert** [comment]
@baltedewit Oh nice! Can't wait to try it when it makes it into the main build. Thanks for working on this.

**Comment by sphlabs** [comment]
Feedback for loop and single clip playback status has now been added in #14 

I've almost finished adding variables. Currently implemented are: status, speed, slot id, clip id and video format.

Timecode is a bit more involved, but hopefully on its way.

**Comment by sphlabs** [comment]
This has now been implemented in the latest build.
